from fila_normal import Fila_Normal
from fila_prioridade import FilaPrioritaria
# fila_teste = Fila_Normal()
# fila_teste.atualiza_fila()
# fila_teste.atualiza_fila()
# fila_teste.atualiza_fila()
# print(fila_teste.chama_cliente(5))
# print(fila_teste.chama_cliente(10))
# print(fila_teste.chama_cliente(6))
fila_teste2 = FilaPrioritaria()
fila_teste2.atualiza_fila()
fila_teste2.atualiza_fila()
fila_teste2.atualiza_fila()
fila_teste2.atualiza_fila()
print(fila_teste2.chama_cliente(5))
print(fila_teste2.chama_cliente(6))
print(fila_teste2.chama_cliente(8))
print(fila_teste2.chama_cliente(9))
fila_teste2.atualiza_fila()
print(fila_teste2.chama_cliente(10))
print(fila_teste2.estatistica('10/11/2002', 205, 'detail'))
